---
title: "OliviaRodrigoData"
output: html_document
---

```{r}
setwd("~/Desktop/oliviarodrigo")
```

```{r}
library(dplyr)
library(tidyverse)
library(tm)
library(tidytext)
```

```{r}
sour <- read.csv("olivia_rodrigo_data.csv", stringsAsFactors = FALSE)
```

replace \n with space, remove punctuations, make everything lower case

```{r}
sour$Lyrics[1]
```

```{r}
gsub("[\n]", "", sour$Lyrics)
```
```{r}
sour$Lyrics <- gsub("[\r\n]", " ", sour$Lyrics)
```
```{r}
sour$Lyrics <- tolower(sour$Lyrics)
```
```{r}
sour$Lyrics <- gsub("i'm", "i am", sour$Lyrics)
sour$Lyrics <- gsub("i'll", "i will", sour$Lyrics)
sour$Lyrics <- gsub("you're", "you are", sour$Lyrics)

```
remove comma in r not between words

```{r}
sour$Lyrics <- gsub("[,()'?]","",sour$Lyrics)
sour$Lyrics <- gsub("[-]"," ",sour$Lyrics)
```

```{r}
sour_df <- tibble(txt = sour$Lyrics) 
```
```{r}
library(janeaustenr)
```
```{r}
tibble(txt = prideprejudice)
```
```{r}
sour_df <- tibble(sour_df)
```
```{r}
library(janeaustenr)
```
```{r}
austen_books() %>%
  unnest_tokens(word, text) %>%
  count(book, word, sort = TRUE)
```
```{r}
sour_tibble <- tibble(line=1:11,text=sour_df$txt)
```
```{r}
manual_stop_words <- c("and", "the","that","to","am","are","so","for","be","it","a","of","in","cause","is","are","get")
```

```{r}
data(stop_words)
```
```{r}
common_words <- sour_tibble %>%
                unnest_tokens(word,text) %>% 
                anti_join(stop_words) %>%
                count(word, sort = TRUE) %>%
                filter(n>10)
```

```{r}
common_words <- common_words$word
```

```{r}
sour$Lyrics[1]
```
```{r}
str_squish(sour$Lyrics[1])
```
```{r}
test_df <- data.frame(table(unlist(strsplit(str_squish(sour$Lyrics[1])," "))))
colnames(test_df) <- c("Word","Frequency")

test_df$Word <- as.character(test_df$Word)
sum(test_df$Word == common_words[1])
```
```{r}
common_words
sour$Title
#11x13
```

```{r}
sour_terms <- data.frame(matrix(NA, nrow = 11, ncol = 13))
```

```{r}
for(i in 1:length(common_words)){
  print(i)
  colnames(sour_terms)[i] <- common_words[i]
}

for(j in 1:length(sour$Title)){
  print(j)
  rownames(sour_terms)[j] <- sour$Title[j]
}

```

```{r}
common_words
```
```{r}
sour_terms[1,]
```
```{r}

for(l in 1:nrow(sour_terms)){
  test_df <- data.frame(table(unlist(strsplit(str_squish(sour$Lyrics[l])," "))))
  colnames(test_df) <- c("Word","Frequency")
  
  test_df$Word <- as.character(test_df$Word)
  counter <- 0
  for(k in 1:length(common_words)){
    if(sum(test_df$Word == common_words[k]) > 0){
      counter <- test_df[test_df$Word == common_words[k],2]
      print(counter)
      sour_terms[l, k] <- counter      
    }else{
      sour_terms[l, k] <- 0
    }
  }
}


```


```{r}
write.csv(sour_terms, "olivia_rodrigo_word_freq.csv")
```